# Generated by Django 4.1 on 2023-06-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_customer_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
